### ISSUE TITLE
Termination

### ISSUE THREAD

**Issue by fsvieira** [mgechev/typed-calc#3]
Hi,

Does the interpreter has any support to guarantee program termination ? Thanks.

**Comment by mgechev** [comment]
@fsvieira if the implementation is correct, the type system should guarantee that. With simply typed lambda calculus, you cannot construct Y combinator.

**Comment by fsvieira** [comment]
Hi, I didn't know that, I saw it now on wiki. But I don't understand if primitive recursive or a form of fixpoint combinator is possible. Is it possible to implement a function like factorial ?
Thanks.

**Comment by mgechev** [comment]
No, it's not. You can look at "Types and Programming Languages", the book this language (and the corresponding article) are inspired from.
